/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.UserDBController;
import com.app.bean.GlobalBeans;
import com.app.bean.UsuarioBean;
import javax.swing.JOptionPane;

/**
 *
 * @author VaioDevelopment
 */
public class frmBuscar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBuscar
     */
    public frmBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jbt_buscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar");

        jLabel1.setText("Indique Nombre de usuario: ");

        jbt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Aceptar2.png"))); // NOI18N
        jbt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(txt_user))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscarActionPerformed
        UsuarioBean user = UserDBController.getUser(txt_user.getText().toString().trim());
        if (user != null) {
            frmUsuarios.setId(user.getId());
            frmUsuarios.cmbPerfil.setSelectedIndex(user.getPerfil());
            frmUsuarios.txtNombres.setText(user.getNombres());
            frmUsuarios.txtApellidos.setText(user.getApellidos());
            frmUsuarios.txtIdUsuario.setText(user.getIdUsuario());
            frmUsuarios.txtClave.setText(user.getClave());
            frmUsuarios.txtConfirClave.setText(user.getClave());

            if (user.getUser_status() == 1) {
                frmUsuarios.chk_status.setSelected(true);
            } else {
                frmUsuarios.chk_status.setSelected(false);
            }
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encontro el usuario indicicado: " + txt_user.getText().toString());
            this.dispose();
        }


    }//GEN-LAST:event_jbt_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbt_buscar;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
