/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.GestionDBController;
import clases.TiempoRegistroBean;
import com.app.bean.GestionBean;
import com.app.coreDB.DriverManagerDb;
import com.app.utils.JLabelTime;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.net.URL;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author VaioDevelopment
 */
public class frmGestion extends javax.swing.JInternalFrame {

    private Object JasperManager;

    /**
     * Creates new form frmGestion
     */
    public frmGestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jlabelTime = new JLabelTime(0,0,0,0);
        jLabel3 = new javax.swing.JLabel();
        jtf_placa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_desc = new javax.swing.JTextField();
        jbt_registrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtf_marca = new javax.swing.JTextField();
        jtf_modelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_color = new javax.swing.JTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión");

        jlabelTime.setText("Fecha y Hora");

        jLabel3.setText("Placa");

        jLabel4.setText("Descripción");

        jbt_registrar.setText("Registrar ingreso");
        jbt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_registrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Marca");

        jLabel6.setText("Modelo");

        jLabel7.setText("Color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabelTime)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addGap(13, 13, 13)
                                        .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(13, 13, 13)
                                        .addComponent(jtf_marca)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jtf_color, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt_registrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelTime)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jbt_registrar)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_registrarActionPerformed

        if (jtf_placa.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el numero de placa del vehiculo");
            jtf_placa.requestFocus();
            return;
        } else if (jtf_marca.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar la marca del vehiculo");
            jtf_marca.requestFocus();
            return;
//        } else if (jtf_color.getText().length() == 0) {
//            JOptionPane.showMessageDialog(rootPane, "Debe indicar el color del vehiculo");
//            jtf_color.requestFocus();
//            return;
//        } else if (jtf_desc.getText().length() == 0) {
//            JOptionPane.showMessageDialog(rootPane, "Debe indicar una observacion");
//            jtf_desc.requestFocus();
//            return;
//        } else if (jtf_modelo.getText().length() == 0) {
//            JOptionPane.showMessageDialog(rootPane, "Debe indicar el modelo del vehiculo");
//            jtf_modelo.requestFocus();
//            return;
        } else {

            GestionBean obj = new GestionBean(
                    jtf_placa.getText().trim(),
                    jtf_marca.getText().trim(),
                    jtf_modelo.getText().trim(),
                    jtf_color.getText().trim(),
                    jtf_desc.getText().trim(),
                    TiempoRegistroBean.getTiempoReg(),
                    0);

            boolean create = GestionDBController.createMovimiento(obj);

            if (create) {
                JOptionPane.showMessageDialog(rootPane, "Registro Creado");

                try {
                    String placa = "Placa: "+jtf_placa.getText();
                    this.generarReporte(placa);
                } catch (JRException ex) {
                    Logger.getLogger(frmGestion.class.getName()).log(Level.SEVERE, null, ex);
                }
                jtf_placa.setText("");
                jtf_marca.setText("");
                jtf_modelo.setText("");
                jtf_color.setText("");
                jtf_desc.setText("");

            } else {
                JOptionPane.showMessageDialog(rootPane, "No se logro crear el registro, contacte al administrador");
            }

        }
    }//GEN-LAST:event_jbt_registrarActionPerformed

    public void generarReporte(String placa) throws JRException {

        DriverManagerDb con = new DriverManagerDb();

        //   String path = "C:\\Users\\VaioDevelopment\\Documents\\proyecto\\final\\ControlParqueadero\\src\\reports\\ticket.jasper";
        Map<String, Object> parameters = new HashMap<String, Object>();
        parameters.put("placa", placa);

        String path = "src\\reports\\ticket.jasper";
        JasperReport jasperReport = null;
        JasperPrint jasperPrint;
        try {
            //se carga el reporte
            //   URL  in=this.getClass().getResource( "ticket.jasper" );
            jasperReport = (JasperReport) JRLoader.loadObjectFromFile(path);
            //se procesa el archivo jasper
            jasperPrint = JasperFillManager.fillReport(jasperReport, (Map<String,Object>)parameters, con.getConexion());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setVisible(true);
            jv.setTitle(path);

            //impresion de reporte
            // TRUE: muestra la ventana de dialogo "preferencias de impresion"
            JasperPrintManager.printReport(jasperPrint, true);
        } catch (JRException ex) {
            System.err.println("Error iReport: " + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbt_registrar;
    private javax.swing.JLabel jlabelTime;
    private javax.swing.JTextField jtf_color;
    private javax.swing.JTextField jtf_desc;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_modelo;
    private javax.swing.JTextField jtf_placa;
    // End of variables declaration//GEN-END:variables
}
