/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.GestionDBController;
import clases.ResultTimeBean;
import clases.TarifasDBController;
import clases.TiempoRegistroBean;
import com.app.bean.GestionBean;
import com.app.bean.TarifasBean;
import com.app.utils.JLabelTime;
import com.app.utils.Utils;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VaioDevelopment
 */
public class frmGestionSalida extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private long horas;
    private long minutos;
    private int registro_id;
    private TarifasBean parametro;

    public frmGestionSalida() {
        //modeloTabla = new DefaultTableModel(null, getColumnas());

        modeloTabla = new DefaultTableModel(null, getColumnas()) {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        parametro = TarifasDBController.getTarifa();
        cargaModelo();
        initComponents();
    }

    private String[] getColumnas() {
        String[] col = new String[]{"Ticke", "Placa", "Marca", "Modelo", "Color", "Fecha/Hora Registro Entrada"};
        return col;
    }

    private void cargaModelo() {
        List<GestionBean> obj = GestionDBController.getAllReg(0);
        if (obj != null) {
            if (obj.size() != 0) {

                for (GestionBean value : obj) {
                    Vector<String> v = new Vector<>();
                    v.add("" + value.getRegistro_id());
                    v.add("" + value.getAuto_placa());
                    v.add("" + value.getAuto_marca());
                    v.add("" + value.getAuto_modelo());
                    v.add("" + value.getAuto_color());
                    v.add("" + value.getFecha_reg_entrada());

                    modeloTabla.addRow(v);
                }

            }
        }
    }

    public void limpiar() {
        int filas = modeloTabla.getRowCount();
        if (filas > 0) {
            for (int i = 0; i < filas; i++) {
                modeloTabla.removeRow(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new JLabelTime(0,0,0,0);
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtf_fecha_salida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_fecha_entrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_total_horas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_total_minutos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_total_pago = new javax.swing.JTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Fecha y Hora");

        jButton1.setText("Registrar Salida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(modeloTabla);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Fecha/Hora Registro Salida :");

        jtf_fecha_salida.setEditable(false);
        jtf_fecha_salida.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Fecha/Hora Registro Entrada :");

        jtf_fecha_entrada.setEditable(false);
        jtf_fecha_entrada.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Total Horas :");

        jtf_total_horas.setEditable(false);
        jtf_total_horas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Total Minutos:");

        jtf_total_minutos.setEditable(false);
        jtf_total_minutos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Total Cancelar :");

        jtf_total_pago.setEditable(false);
        jtf_total_pago.setBackground(new java.awt.Color(255, 255, 255));
        jtf_total_pago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 78, Short.MAX_VALUE)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_total_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtf_total_pago)
                                .addGap(296, 296, 296)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_total_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_total_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_total_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(jtf_total_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened


    }//GEN-LAST:event_formInternalFrameOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fsel = jTable1.getSelectedRow();
        if (fsel == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro");
        } else {
            registro_id = Integer.valueOf(jTable1.getValueAt(fsel, 0).toString());
            jtf_fecha_salida.setText(TiempoRegistroBean.getTiempoReg());
            jtf_fecha_entrada.setText(jTable1.getValueAt(fsel, 5).toString());
            ResultTimeBean obje = Utils.DiferenciaFechas(jtf_fecha_entrada.getText(), jtf_fecha_salida.getText());

            horas = obje.getHoras();
            minutos = obje.getMinutos();

            jtf_total_horas.setText("" + obje.getHoras());
            jtf_total_minutos.setText("" + obje.getMinutos());
        }

        jtf_total_pago.setText("" + getTotalPagar(horas, minutos));


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GestionBean obj = new GestionBean(
                registro_id,
                jtf_fecha_salida.getText().toString(),
                Integer.valueOf(jtf_total_horas.getText().toString()),
                Integer.valueOf(jtf_total_minutos.getText().toString()),
                Double.valueOf(jtf_total_pago.getText().toString()),
                1);
        boolean update = GestionDBController.setGestion(obj);

        if (update) {
            JOptionPane.showMessageDialog(rootPane, "Registro de salida procesado");
            registro_id = 0;
            jtf_fecha_salida.setText("");
            jtf_fecha_entrada.setText("");
            horas = 0;
            minutos = 0;
            jtf_total_horas.setText("");
            jtf_total_minutos.setText("");
            jtf_total_pago.setText("");
            limpiar();
            cargaModelo();

        } else {
            JOptionPane.showMessageDialog(rootPane, "No se logro realizar la operacion, contacte al administrador");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public double getTotalPagar(long hor, long min) {
        double totalPago = 0.00;
        //Pregunto si la horas son igual a 0 o menos a 12 horas
        if (hor >= 0 && hor < 12) {
            totalPago = ((hor * 60) * Double.valueOf(parametro.getCosto_min()) + (min * Double.valueOf(parametro.getCosto_min())));
            if (totalPago > Double.valueOf(parametro.getCosto_max_hora())) {
                totalPago = Double.valueOf(parametro.getCosto_max_hora());
            }
        } else {
            if (hor >= 12 && hor < 24) {
                long horDif = hor - 12L;
                if (horDif <= 12) {
                    totalPago = ((Double.valueOf(parametro.getCosto_max_hora())) + ((horDif * 60) * Double.valueOf(parametro.getCosto_min())) + ((min * Double.valueOf(parametro.getCosto_min()))));
                    if (totalPago > (Double.valueOf(parametro.getCosto_max_hora())) * 2) {
                        totalPago = (Double.valueOf(parametro.getCosto_max_hora()) * 2);
                    }
                }
            } else {
                if (hor >= 24 && hor < 36) {
                    long horDif = hor - 24L;
                    if (horDif <= 12) {
                        totalPago = ((Double.valueOf(parametro.getCosto_max_hora()) * 2) + ((horDif * 60) * Double.valueOf(parametro.getCosto_min()) + (min * Double.valueOf(parametro.getCosto_min()))));
                        if (totalPago > (Double.valueOf(parametro.getCosto_max_hora())) * 3) {
                            totalPago = (Double.valueOf(parametro.getCosto_max_hora()) * 3);
                        }
                    }

                }else{
                    long horDif = hor - 36L;
                    if (horDif <= 12) {
                        totalPago = ((Double.valueOf(parametro.getCosto_max_hora()) * 3) + ((horDif * 60) * Double.valueOf(parametro.getCosto_min()) + (min * Double.valueOf(parametro.getCosto_min()))));
                        if (totalPago > (Double.valueOf(parametro.getCosto_max_hora())) * 4) {
                            totalPago = (Double.valueOf(parametro.getCosto_max_hora()) * 4);
                        }
                    }else{
                     horDif = hor - 48L;
                    totalPago = (Double.valueOf(parametro.getCosto_max_hora()) * 4)+ ((horDif * 60) * Double.valueOf(parametro.getCosto_min()) + (min * Double.valueOf(parametro.getCosto_min())));
                    }
                }
            }
        }

        return totalPago;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGestionSalida().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jtf_fecha_entrada;
    private javax.swing.JTextField jtf_fecha_salida;
    private javax.swing.JTextField jtf_total_horas;
    private javax.swing.JTextField jtf_total_minutos;
    private javax.swing.JTextField jtf_total_pago;
    // End of variables declaration//GEN-END:variables
}
