/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.ParqueaderoDBController;
import com.app.bean.ParqueaderoBean;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class frmParqueadero extends javax.swing.JInternalFrame {

    private int typeCase = 0;
    private int id;

    public frmParqueadero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_rif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cupos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_moneda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nombreDocumento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_header_in = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_header_out = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_footer_in = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_footer_out = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Parqueadero");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Nombre Parqueadero:");

        jLabel2.setText("Identificación:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Cupos:");

        jLabel6.setText("Simbolo Moneda:");

        jLabel7.setText("Nombre del Documento:");

        jLabel8.setText("Cabecera Ticket de Entrada");
        jLabel8.setToolTipText("");

        jLabel9.setText("Cabecera Ticket de Salida");
        jLabel9.setToolTipText("");

        txt_header_in.setColumns(20);
        txt_header_in.setRows(5);
        jScrollPane1.setViewportView(txt_header_in);

        txt_header_out.setColumns(20);
        txt_header_out.setRows(5);
        jScrollPane2.setViewportView(txt_header_out);

        jLabel10.setText("Pie Ticket de Entrada");
        jLabel10.setToolTipText("");

        txt_footer_in.setColumns(20);
        txt_footer_in.setRows(5);
        jScrollPane3.setViewportView(txt_footer_in);

        jLabel11.setText("Pie Ticket de Salida");
        jLabel11.setToolTipText("");

        txt_footer_out.setColumns(20);
        txt_footer_out.setRows(5);
        jScrollPane4.setViewportView(txt_footer_out);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        jButton1.setToolTipText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editar.png"))); // NOI18N
        jButton2.setToolTipText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancelar.png"))); // NOI18N
        jButton3.setToolTipText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_telefono)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_cupos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_moneda, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addComponent(txt_rif)
                    .addComponent(txt_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_direccion)
                    .addComponent(txt_nombreDocumento))
                .addGap(0, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(106, 106, 106)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(74, 74, 74)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_rif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_cupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_nombreDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txt_name.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el nombre del local");
            txt_name.requestFocus();
            return;
        } else if (txt_rif.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el numero de identificacion");
            txt_rif.requestFocus();
            return;
        } else if (txt_direccion.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar la direccion");
            txt_direccion.requestFocus();
            return;
        } else if (txt_telefono.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el numero de telefono");
            txt_telefono.requestFocus();
            return;
        } else if ((Integer) txt_cupos.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el numero de cupos disponibles");
            txt_cupos.requestFocus();
            return;
        } else if (txt_moneda.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el simbolo del tipo de moneda a usar");
            txt_moneda.requestFocus();
            return;
        } else if (txt_nombreDocumento.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el nombre del Documento");
            txt_nombreDocumento.requestFocus();
            return;
        } else if (txt_header_in.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el encabezado del ticke de entrada");
            txt_header_in.requestFocus();
            return;
        } else if (txt_header_out.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el encabezado del ticke de salida");
            txt_header_out.requestFocus();
            return;
        } else if (txt_footer_in.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el pie del ticke de entrada");
            txt_footer_in.requestFocus();
            return;
        } else if (txt_footer_out.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe indicar el pie del ticke de salida");
            txt_footer_out.requestFocus();
            return;
        } else {

            ParqueaderoBean obj = new ParqueaderoBean(
                    txt_name.getText().toString().trim(),
                    txt_rif.getText().toString().trim(),
                    txt_direccion.getText().toString().trim(),
                    txt_telefono.getText().toString().trim(),
                    Integer.valueOf(txt_cupos.getText().toString().trim()),
                    txt_moneda.getText().toString().trim(),
                    txt_nombreDocumento.getText().toString().trim(),
                    txt_header_in.getText().toString().trim(),
                    txt_header_out.getText().toString().trim(),
                    txt_footer_in.getText().toString().trim(),
                    txt_footer_out.getText().toString().trim()
            );

            switch (typeCase) {
                case 0://guardo registro

                    boolean value = ParqueaderoDBController.createParqueadero(obj);

                    if (value) {
                        JOptionPane.showMessageDialog(rootPane, "Registro Creado.");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Registro no se logro crear, contacte al administrador.");
                    }
                    break;
                case 1://actualizo registro
                    obj.setId(id);
                    boolean val = ParqueaderoDBController.setParqueadero(obj);
                    if (val) {
                        JOptionPane.showMessageDialog(rootPane, "Registro fue actualizado.");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Registro no se logro actualizar, contacte al administrador.");
                    }
                    break;
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        ParqueaderoBean obj = ParqueaderoDBController.getParqueadero();
        if (obj == null) {
            typeCase = 0;
            JOptionPane.showMessageDialog(rootPane, "No existe un registro del Local, por favor\nregistre el local.");
        } else {
            typeCase = 0;
            id = obj.getId();
            txt_name.setText(obj.getName());
            txt_rif.setText(obj.getIdentificacion());
            txt_direccion.setText(obj.getDireccion());
            txt_telefono.setText(obj.getTelefono());
            txt_cupos.setText(String.valueOf(obj.getCupos()));
            txt_moneda.setText(obj.getSimMoneda());
            txt_nombreDocumento.setText(obj.getNombreDocumento());
            txt_header_in.setText(obj.getHeader_ticket_in());
            txt_header_out.setText(obj.getHeader_ticket_out());
            txt_footer_in.setText(obj.getFooter_ticket_in());
            txt_footer_out.setText(obj.getFooter_ticket_out());

            txt_name.setEnabled(false);
            txt_rif.setEnabled(false);
            txt_direccion.setEnabled(false);
            txt_telefono.setEnabled(false);
            txt_cupos.setEnabled(false);
            txt_moneda.setEnabled(false);
            txt_nombreDocumento.setEnabled(false);
            txt_header_in.setEnabled(false);
            txt_header_out.setEnabled(false);
            txt_footer_in.setEnabled(false);
            txt_footer_out.setEnabled(false);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        typeCase = 1;
        txt_name.setEnabled(true);
        txt_rif.setEnabled(true);
        txt_direccion.setEnabled(true);
        txt_telefono.setEnabled(true);
        txt_cupos.setEnabled(true);
        txt_moneda.setEnabled(true);
        txt_nombreDocumento.setEnabled(true);
        txt_header_in.setEnabled(true);
        txt_header_out.setEnabled(true);
        txt_footer_in.setEnabled(true);
        txt_footer_out.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txt_name.setEnabled(false);
        txt_rif.setEnabled(false);
        txt_direccion.setEnabled(false);
        txt_telefono.setEnabled(false);
        txt_cupos.setEnabled(false);
        txt_moneda.setEnabled(false);
        txt_nombreDocumento.setEnabled(false);
        txt_header_in.setEnabled(false);
        txt_header_out.setEnabled(false);
        txt_footer_in.setEnabled(false);
        txt_footer_out.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txt_cupos;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextArea txt_footer_in;
    private javax.swing.JTextArea txt_footer_out;
    private javax.swing.JTextArea txt_header_in;
    private javax.swing.JTextArea txt_header_out;
    private javax.swing.JTextField txt_moneda;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nombreDocumento;
    private javax.swing.JTextField txt_rif;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
